name: Create ZIP
on:
  push:
    branches: ["main"]
    paths:
      - 'config/_default/**'
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r config-default.zip config/_default
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - uses: actions/upload-artifact@v3
        with:
          name: config-default
          path: config-default.zip
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: config-default.zip
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
